
<pre>
<center><b><h1>Machine Learning</b></center>

<center><b><h1>Lab - 3</b></center>    
<pre>

# 📱 Lab: Scikit-Learn Fundamentals (Google Play Store)

**Objective:** Transition from manual data cleaning to automated Machine Learning preprocessing using Scikit-Learn.

**Prerequisites:**
* Ensure you have the `googleplaystore_cleaned.csv` file (from the previous lab) in this folder.

### 1. Load Preprocessed Data
**Instruction:** Load the dataset you cleaned in the previous lab. This dataset should already have `Installs`, `Price`, and `Reviews` converted to numbers.

In [69]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("googleplaystore_cleaned.csv")
df

,Unnamed: 0.1,Unnamed: 0,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,0,0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,NaN,159.0,19000000.0,10000.0,Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,1,1,Coloring book moana,ART_AND_DESIGN,NaN,967.0,14000000.0,500000.0,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,2,2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,NaN,87510.0,8700000.0,5000000.0,Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,3,3,Sketch - Draw & Paint,ART_AND_DESIGN,NaN,215644.0,25000000.0,50000000.0,Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,4,4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,NaN,967.0,2800000.0,100000.0,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,10836,10836,Sya9a Maroc - FR,FAMILY,NaN,38.0,53000000.0,5000.0,Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,10837,10837,Fr. Mike Schmitz Audio Teachings,FAMILY,NaN,4.0,3600000.0,100.0,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,10838,10838,Parkinson Exercices FR,MEDICAL,NaN,3.0,9500000.0,1000.0,Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,10839,10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,NaN,114.0,NaN,1000.0,Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,10840,10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,NaN,398307.0,19000000.0,10000000.0,Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

### Intro to Scikit-Learn
**What is Scikit-Learn?**
It is the standard library for Machine Learning in Python. We use it for:
1.  **Preprocessing:** Scaling numbers and encoding text.
2.  **Modeling:** Training algorithms.
3.  **Evaluation:** Checking accuracy.

**Task:** Import `sklearn` and check the version.

In [11]:
import sklearn

In [15]:
##__version__
print(f"The scikit-learn version is: {sklearn.__version__}")

The scikit-learn version is: 1.5.1

### 3.  Train_Test_Split
**Concept:** We split data to prevent "Overfitting". The model learns from the **Train** set and is tested on the **Test** set.

**Task:** 
1. Define `X` (Features: everything except Rating/App) and `y` (Target: Rating).
2. Split the data (80% Train, 20% Test).

In [32]:
# train_test_split
from sklearn.model_selection import train_test_split

X = df.drop(["App", "Rating"], axis=1)
y = df["Rating"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)

Training Shape: (8672, 13)
Testing Shape: (2169, 13)

In [42]:
X_train

,Unnamed: 0.1,Unnamed: 0,Category,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
6762,6762,6762,SOCIAL,22.0,8700000.0,1000.0,Free,0,Teen,Social,"August 5, 2018",31.1.4,4.3 and up
401,401,401,COMMUNICATION,346982.0,NaN,10000000.0,Free,0,Everyone,Communication,"January 23, 2018",Varies with device,4.1 and up
7420,7420,7420,VIDEO_PLAYERS,3.0,2800000.0,500.0,Free,0,Everyone,Video Players & Editors,"November 26, 2017",1.0,4.0 and up
1631,1631,1631,LIFESTYLE,16637.0,10000000.0,1000000.0,Free,0,Everyone,Lifestyle,"June 18, 2017",1.8,2.3 and up
6475,6475,6475,MEDICAL,3.0,10000000.0,100.0,Free,0,Everyone,Medical,"April 9, 2018",1.0.8,4.3 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,5734,5734,PERSONALIZATION,0.0,NaN,100000.0,Free,0,Everyone,Personalization,"March 17, 2017",Varies with device,Varies with device
5191,5191,5191,PRODUCTIVITY,25627.0,9800000.0,1000000.0,Free,0,Everyone,Productivity,"August 5, 2018",132,5.0 and up
5390,5390,5390,BUSINESS,23729.0,24000000.0,1000000.0,Free,0,Everyone,Business,"May 14, 2018",7.2,4.4 and up
860,860,860,ENTERTAINMENT,10939.0,4600000.0,10000000.0,Free,0,Everyone,Entertainment,"April 28, 2016",2.05.0010,5.0 and up
7270,7270,7270,HEALTH_AND_FITNESS,4.0,14000000.0,100.0,Free,0,Everyone,Health & Fitness,"July 9, 2018",4.2.2,4.1 and up

### 4. 📏 Scaling Numerical Data (StandardScaler)
**Concept:** `Installs` (Millions) are much larger than `Rating` (1-5). We scale them so the model treats them equally.

**Task:** Use `StandardScaler` on the numerical columns.

In [73]:
#StandardScaler()
#fit_transform()
from sklearn.preprocessing import StandardScaler

numeric_cols = ["Rating", "Reviews", "Size", "Installs"]

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df[numeric_cols])
scaled_df = pd.DataFrame(scaled_data, columns=numeric_cols)
scaled_df.head()

C:\Users\priya\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1137: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
C:\Users\priya\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1142: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
C:\Users\priya\anaconda3\Lib\site-packages\sklearn\utils\extmath.py:1162: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

   Rating   Reviews      Size  Installs
0     NaN -0.151657 -0.111412 -0.181761
1     NaN -0.151381 -0.332774 -0.175998
2     NaN -0.121820 -0.567417 -0.123073
3     NaN -0.078053  0.154221  0.406180
4     NaN -0.151381 -0.828623 -0.180703

### 5. 🔠 Encoding Categorical Data
**Concept:** Models need numbers, not text like "Business" or "Teen".

**Method A: Pandas `get_dummies` (Simple)**

In [91]:
import pandas as pd

data = {
    'App_ID': [3254, 4353, 786, 6149, 449],
    'Age_Rating': ['Everyone', 'Everyone', 'Everyone 10+', 'Teen', 'Teen']
}

df = pd.DataFrame(data)

encoded_df = pd.get_dummies(df, columns=['Age_Rating'], dtype=bool)

print(encoded_df)

   App_ID  Age_Rating_Everyone  Age_Rating_Everyone 10+  Age_Rating_Teen
0    3254                 True                    False            False
1    4353                 True                    False            False
2     786                False                     True            False
3    6149                False                    False             True
4     449                False                    False             True

In [9]:
#get_dummies

      Adults only 18+  Everyone  Everyone 10+  Mature 17+   Teen  Unrated
3254            False      True         False       False  False    False
4353            False      True         False       False  False    False
786             False     False          True       False  False    False
6149            False     False         False       False   True    False
449             False     False         False       False   True    False

**Method B: Sklearn `OneHotEncoder` (Professional)**

In [17]:
#OneHotEncoder
#fit_transform

Encoded Shape: (7056, 33)

### 6. 🚀 The Full Pipeline: ColumnTransformer
**Concept:** Instead of doing steps 4 and 5 manually, we wrap them in one object.

**Task:** Create a `ColumnTransformer` that Scales numerical data AND Encodes categorical data at the same time.

In [19]:
from sklearn.compose import ColumnTransformer

In [20]:
numeric_features = ['Reviews', 'Size', 'Installs', 'Price']
categorical_features = ['Category', 'Content Rating']

In [21]:
# Create ColumnTransformer

In [24]:
from sklearn.pipeline import Pipeline